---
- name: Build and push Docker image to ECR (local)
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Run shell script to build and push Docker image
      command: ./scripts/push-to-ecr.sh
